"""Generate a small UI bundle for the JoyCon helper app.

A UI bundle is a folder containing:
- theme.json
- background-left.svg
- background-right.svg
- background-both.svg
- background.svg (compat copy)
- layout.json
- icons.svg (optional)
- components.svg (optional)
- README.md

This script is intentionally dependency-free (stdlib only) so it can run anywhere.

Usage:
    python tools/generate_ui_bundle.py --out ./.ui-bundle
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Tuple


DEFAULT_THEME = {
    "name": "sketchbook-ink",
    "version": 1,
    "colors": {
        "bg": "#e8d8b8",
        "panel": "#f2e8d0",
        "panel2": "#e2d0a8",
        "text": "#2a1f0e",
        "muted": "#6b5d48",
        "border": "#b09878",
        "accent": "#2f4a9e",
        "accent2": "#2b6a4b",
        "danger": "#b42318",
        "warning": "#a16207",
    },
    "typography": {
        # Sketch/handwritten font — Segoe Print ships with Windows; Tkinter falls back to system font gracefully.
        "font_family": "Segoe Print",
        "font_size": 10,
        "mono_family": "Consolas",
        "mono_size": 10,
    },
    "spacing": {"xs": 4, "sm": 8, "md": 12, "lg": 16},
    "radii": {"sm": 6, "md": 10, "lg": 14},
}


DARK_THEME = {
    "name": "sketchbook-ink-dark",
    "version": 1,
    "colors": {
        "bg": "#1e1a14",
        "panel": "#2a2418",
        "panel2": "#342a1e",
        "text": "#d4c8aa",
        "muted": "#8a7d68",
        "border": "#5a4a38",
        "accent": "#5c8ae6",
        "accent2": "#4aad72",
        "danger": "#e04838",
        "warning": "#d4a020",
    },
    "typography": {
        "font_family": "Segoe Print",
        "font_size": 10,
        "mono_family": "Consolas",
        "mono_size": 10,
    },
    "spacing": {"xs": 4, "sm": 8, "md": 12, "lg": 16},
    "radii": {"sm": 6, "md": 10, "lg": 14},
}


DEFAULT_LAYOUT = {
    "window": {"width": 980, "height": 680},
    "regions": [
        {"id": "topbar", "type": "row", "items": ["port", "baud", "connect", "bt_status"]},
        {"id": "main", "type": "split", "left": "tabs", "right": "actions"},
        {"id": "log", "type": "panel", "title": "Device log / events"},
    ],
    "tabs": ["Profile", "Macros", "Stick", "Share", "Overlay", "Controller"],
}


BUNDLE_README = """# UI bundle

This folder is a generated UI bundle for the JoyCon Bridge helper app.

Files:

- theme.json: semantic tokens (colors/typography/spacing)
- background-left.svg: optional background artwork (Left state)
- background-right.svg: optional background artwork (Right state)
- background-both.svg: optional background artwork (Both state)
- background.svg: compatibility copy (currently the same as background-both.svg)
- layout.json: layout metadata for documentation / future UI refactors
- icons.svg: optional icon set
- components.svg: optional component sheet
- joycons.png: compatibility overlay artwork for older backgrounds/tools
- joycons-both.png: full-color overlay artwork for both connected
- joycons-left.png: left-connected overlay artwork with the right side greyed out
- joycons-right.png: right-connected overlay artwork with the left side greyed out
- joycons-none.png: fully-grey overlay artwork for no controllers connected

Two bundles are generated by default:
- `.ui-bundle/` — light theme (torn parchment on dark desk)
- `.ui-bundle-dark/` — dark theme (same torn parchment aesthetic, dark-inverted)

This bundle is *not automatically loaded* by the helper app.
"""


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _rewrite_bundle_svg(svg_text: str, *, dark: bool = False) -> str:
    # Keep docs-friendly relative paths in repo sources, but ensure generated bundle
    # SVGs are self-contained within the output folder.
    text = svg_text.replace("../../joycons.png", "joycons.png")
    text = text.replace("../../joycons-dark.png", "joycons.png")
    return text


LIGHT_OVERLAYS = {
    "joycons.png": Path("joycons.png"),
    "joycons-both.png": Path("docs/ui/assets/joycons-both.png"),
    "joycons-left.png": Path("docs/ui/assets/joycons-left.png"),
    "joycons-right.png": Path("docs/ui/assets/joycons-right.png"),
    "joycons-none.png": Path("docs/ui/assets/joycons-none.png"),
}

DARK_OVERLAYS = {
    "joycons.png": Path("joycons-dark.png"),
    "joycons-both.png": Path("docs/ui/assets/joycons-dark-both.png"),
    "joycons-left.png": Path("docs/ui/assets/joycons-dark-left.png"),
    "joycons-right.png": Path("docs/ui/assets/joycons-dark-right.png"),
    "joycons-none.png": Path("docs/ui/assets/joycons-dark-none.png"),
}


def _write_bundle(
    out_dir: Path,
    theme: dict,
    bg_left_path: Path,
    bg_right_path: Path,
    bg_both_path: Path,
    icons_path: Path | None,
    components_path: Path | None,
    *,
    dark: bool = False,
) -> None:
    """Write a single UI bundle into *out_dir*."""
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "theme.json").write_text(json.dumps(theme, indent=2), encoding="utf-8")
    (out_dir / "layout.json").write_text(json.dumps(DEFAULT_LAYOUT, indent=2), encoding="utf-8")
    (out_dir / "background-left.svg").write_text(_rewrite_bundle_svg(_read_text(bg_left_path), dark=dark), encoding="utf-8")
    (out_dir / "background-right.svg").write_text(_rewrite_bundle_svg(_read_text(bg_right_path), dark=dark), encoding="utf-8")
    (out_dir / "background-both.svg").write_text(_rewrite_bundle_svg(_read_text(bg_both_path), dark=dark), encoding="utf-8")
    # Keep a compatibility copy for older docs/tools.
    (out_dir / "background.svg").write_text(_rewrite_bundle_svg(_read_text(bg_both_path), dark=dark), encoding="utf-8")

    overlays = DARK_OVERLAYS if dark else LIGHT_OVERLAYS
    for name, overlay_path in overlays.items():
        if overlay_path.exists():
            try:
                (out_dir / name).write_bytes(overlay_path.read_bytes())
            except Exception:
                pass

    if icons_path and icons_path.exists():
        (out_dir / "icons.svg").write_text(_read_text(icons_path), encoding="utf-8")

    if components_path and components_path.exists():
        (out_dir / "components.svg").write_text(_read_text(components_path), encoding="utf-8")

    (out_dir / "README.md").write_text(BUNDLE_README, encoding="utf-8")

    print(f"  Wrote bundle to: {out_dir}")


def _resolve_bg_paths(args, prefix: str) -> Tuple[Path, Path, Path]:
    """Resolve background SVG paths for a given variant prefix ('background' or 'dark_background')."""
    single = getattr(args, prefix, None)
    if single:
        p = Path(single)
        return p, p, p

    left_attr = f"{prefix}_left"
    right_attr = f"{prefix}_right"
    both_attr = f"{prefix}_both"

    left = Path(getattr(args, left_attr))
    right = Path(getattr(args, right_attr))
    both = Path(getattr(args, both_attr))

    missing = [p for p in (left, right, both) if not p.exists()]
    if missing:
        # Fallback: dark uses the single dark background file, light uses background.svg
        if "dark" in prefix:
            legacy = Path("docs/ui/background-dark.svg")
        else:
            legacy = Path("docs/ui/background.svg")
        if legacy.exists():
            return legacy, legacy, legacy
        raise SystemExit(f"background(s) not found ({prefix}): " + ", ".join(str(p) for p in missing))

    return left, right, both


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="Output folder for the light bundle")
    ap.add_argument(
        "--background",
        default=None,
        help=(
            "Legacy: single background SVG to include for all states. "
            "If provided, it will be used as background-left/right/both, and also written as background.svg."
        ),
    )
    ap.add_argument(
        "--background-left",
        default="docs/ui/background-left.svg",
        help="Path to background-left.svg to include (default: docs/ui/background-left.svg)",
    )
    ap.add_argument(
        "--background-right",
        default="docs/ui/background-right.svg",
        help="Path to background-right.svg to include (default: docs/ui/background-right.svg)",
    )
    ap.add_argument(
        "--background-both",
        default="docs/ui/background-both.svg",
        help="Path to background-both.svg to include (default: docs/ui/background-both.svg)",
    )
    ap.add_argument(
        "--icons",
        default="docs/ui/assets/icons.svg",
        help="Path to icons.svg to include when present (default: docs/ui/assets/icons.svg)",
    )
    ap.add_argument(
        "--components",
        default="docs/ui/assets/components.svg",
        help="Path to components.svg to include when present (default: docs/ui/assets/components.svg)",
    )
    ap.add_argument(
        "--dark-out",
        default=None,
        help="Output folder for the dark bundle (default: <out>-dark)",
    )
    ap.add_argument(
        "--dark-background",
        default=None,
        help="Single dark background SVG for all states (overrides --dark-background-left/right/both)",
    )
    ap.add_argument(
        "--dark-background-left",
        default="docs/ui/background-dark.svg",
        help="Path to dark background-left.svg (default: docs/ui/background-dark.svg)",
    )
    ap.add_argument(
        "--dark-background-right",
        default="docs/ui/background-dark.svg",
        help="Path to dark background-right.svg (default: docs/ui/background-dark.svg)",
    )
    ap.add_argument(
        "--dark-background-both",
        default="docs/ui/background-dark.svg",
        help="Path to dark background-both.svg (default: docs/ui/background-dark.svg)",
    )
    ap.add_argument(
        "--dark-icons",
        default="docs/ui/assets/icons-dark.svg",
        help="Path to dark icons.svg (default: docs/ui/assets/icons-dark.svg)",
    )
    ap.add_argument(
        "--dark-components",
        default="docs/ui/assets/components-dark.svg",
        help="Path to dark components.svg (default: docs/ui/assets/components-dark.svg)",
    )
    ap.add_argument(
        "--no-dark",
        action="store_true",
        help="Skip generating the dark bundle",
    )
    args = ap.parse_args()

    # ── Light bundle ──
    out_dir = Path(args.out)
    bg_left, bg_right, bg_both = _resolve_bg_paths(args, "background")

    print("Light bundle:")
    _write_bundle(out_dir, DEFAULT_THEME, bg_left, bg_right, bg_both,
                  Path(args.icons), Path(args.components))

    # ── Dark bundle ──
    if not args.no_dark:
        dark_out = Path(args.dark_out) if args.dark_out else Path(str(args.out) + "-dark")
        dark_left, dark_right, dark_both = _resolve_bg_paths(args, "dark_background")

        print("Dark bundle:")
        _write_bundle(dark_out, DARK_THEME, dark_left, dark_right, dark_both,
                      Path(args.dark_icons), Path(args.dark_components),
                      dark=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
