"""Generate a small UI bundle for the Bind Bandit app.

A UI bundle is a folder containing:
- theme.json
- layout.json
- PNG overlays (joycons, m913, background, pinouts)
- README.md

This script is intentionally dependency-free (stdlib only) so it can run anywhere.

Usage:
    python tools/generate_ui_bundle.py --out ./.ui-bundle
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path



DEFAULT_THEME = {
    "name": "sketchbook-ink",
    "version": 2,
    "colors": {
        "bg": "#e8d8b8",
        "panel": "#f2e8d0",
        "panel2": "#e2d0a8",
        "text": "#2a1f0e",
        "muted": "#6b5d48",
        "border": "#b09878",
        "accent": "#2f4a9e",
        "accent2": "#2b6a4b",
        "danger": "#b42318",
        "warning": "#a16207",
        "active": "#2b6a4b",
        "conflict": "#b42318",
        "modified": "#a16207",
        "selected": "#2f4a9e",
        "pulse_bright": "#60c090",
        "timeline_press": "#2b6a4b",
        "timeline_release": "#6b5d48",
    },
    "typography": {
        # Sketch/handwritten font — Segoe Print ships with Windows; Tkinter falls back to system font gracefully.
        "font_family": "Segoe Print",
        "font_size": 10,
        "mono_family": "Consolas",
        "mono_size": 10,
    },
    "spacing": {"xs": 4, "sm": 8, "md": 12, "lg": 16},
    "radii": {"sm": 6, "md": 10, "lg": 14},
}


DARK_THEME = {
    "name": "sketchbook-ink-dark",
    "version": 2,
    "colors": {
        "bg": "#10141c",
        "panel": "#181e2c",
        "panel2": "#202838",
        "text": "#a8bcd0",
        "muted": "#6888aa",
        "border": "#2a3a54",
        "accent": "#4a7cc8",
        "accent2": "#3a8a5c",
        "danger": "#c84848",
        "warning": "#b89030",
        "active": "#3a8a5c",
        "conflict": "#c84848",
        "modified": "#b89030",
        "selected": "#4a7cc8",
        "pulse_bright": "#60c898",
        "timeline_press": "#3a8a5c",
        "timeline_release": "#6888aa",
    },
    "typography": {
        "font_family": "Segoe Print",
        "font_size": 10,
        "mono_family": "Consolas",
        "mono_size": 10,
    },
    "spacing": {"xs": 4, "sm": 8, "md": 12, "lg": 16},
    "radii": {"sm": 6, "md": 10, "lg": 14},
}


DEFAULT_LAYOUT = {
    "window": {"width": 980, "height": 720},
    "regions": [
        {"id": "topbar", "type": "row", "items": ["port", "baud", "connect", "bt_status"]},
        {"id": "main", "type": "split", "left": "tabs", "right": "actions"},
        {"id": "log", "type": "panel", "title": "Device log / events"},
    ],
    "tabs": ["Profile", "Macros", "Stick", "Share", "Overlay", "Controller", "Input Test", "Mouse"],
    "features": {
        "press_to_bind": True,
        "right_click_context": True,
        "pulse_animation": True,
        "slot_quick_select": 4,
        "safe_mode": True,
        "conflict_detection": True,
        "conflict_auto_fix": True,
        "chording": True,
        "tap_hold": True,
        "event_timeline": True,
        "layers": 4,
        "undo_redo": True,
        "undo_max_depth": 50,
        "guided_wizard": True,
        "intent_mapping": True,
        "smart_defaults": True,
        "smart_search": True,
        "sandbox_mode": True,
        "adaptive_ui": True,
        "mode_indicator": True,
        "ghost_labels": True,
        "visual_layer_stack": True,
        "explain_mapping": True,
        "lock_critical_inputs": True,
        "feedback_sounds": True,
        "community_presets": True,
        "drag_and_drop": False,
        "m913_mouse": True,
        "m913_multi_device": True,
        "m913_sister_profiles": True,
    },
}


BUNDLE_README = """# UI bundle

This folder is a generated UI bundle for the Bind Bandit app.

Files:

- theme.json: semantic tokens (colors/typography/spacing)
- layout.json: layout metadata for documentation / future UI refactors
- background.png: full-window background image (light theme)
- background-dark.png: full-window background image (dark theme)
- joycons.png: compatibility overlay artwork for older backgrounds/tools
- joycons-both.png: full-color overlay artwork for both connected
- joycons-left.png: left-connected overlay artwork with the right side greyed out
- joycons-right.png: right-connected overlay artwork with the left side greyed out
- joycons-none.png: fully-grey overlay artwork for no controllers connected
- m913.png: M913 mouse overlay artwork (connected state)
- m913-none.png: M913 mouse overlay artwork (disconnected state)
- m913_Incedius.png: IncediusMod mouse overlay artwork (connected state)
- m913_Incedius-none.png: IncediusMod mouse overlay artwork (disconnected state)
- pinouts.png: ESP32/ESP32-S3 board pinout reference diagram

Two bundles are generated by default:
- `.ui-bundle/` — light theme (torn parchment on dark desk)
- `.ui-bundle-dark/` — dark theme (same torn parchment aesthetic, dark-inverted)

This bundle is *not automatically loaded* by the helper app.
"""


LIGHT_OVERLAYS = {
    "joycons.png": Path("joycons.png"),
    "joycons-both.png": Path("docs/ui/assets/joycons-both.png"),
    "joycons-left.png": Path("docs/ui/assets/joycons-left.png"),
    "joycons-right.png": Path("docs/ui/assets/joycons-right.png"),
    "joycons-none.png": Path("docs/ui/assets/joycons-none.png"),
    "m913.png": Path("docs/ui/assets/m913.png"),
    "m913-none.png": Path("docs/ui/assets/m913-none.png"),
    "m913_Incedius.png": Path("docs/ui/assets/m913_Incedius.png"),
    "m913_Incedius-none.png": Path("docs/ui/assets/m913_Incedius-none.png"),
    "background.png": Path("docs/ui/background.png"),
    "pinouts.png": Path("docs/ui/assets/pinouts.png"),
}

DARK_OVERLAYS = {
    "joycons.png": Path("joycons-dark.png"),
    "joycons-both.png": Path("docs/ui/assets/joycons-dark-both.png"),
    "joycons-left.png": Path("docs/ui/assets/joycons-dark-left.png"),
    "joycons-right.png": Path("docs/ui/assets/joycons-dark-right.png"),
    "joycons-none.png": Path("docs/ui/assets/joycons-dark-none.png"),
    "m913.png": Path("docs/ui/assets/m913-dark.png"),
    "m913-none.png": Path("docs/ui/assets/m913-dark-none.png"),
    "m913_Incedius-dark.png": Path("docs/ui/assets/m913_Incedius-dark.png"),
    "m913_Incedius-dark-none.png": Path("docs/ui/assets/m913_Incedius-dark-none.png"),
    "background-dark.png": Path("docs/ui/background-dark.png"),
    "pinouts.png": Path("docs/ui/assets/pinouts.png"),
}


def _write_bundle(
    out_dir: Path,
    theme: dict,
    *,
    dark: bool = False,
) -> None:
    """Write a single UI bundle into *out_dir*."""
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "theme.json").write_text(json.dumps(theme, indent=2), encoding="utf-8")
    (out_dir / "layout.json").write_text(json.dumps(DEFAULT_LAYOUT, indent=2), encoding="utf-8")

    overlays = DARK_OVERLAYS if dark else LIGHT_OVERLAYS
    for name, overlay_path in overlays.items():
        if overlay_path.exists():
            try:
                (out_dir / name).write_bytes(overlay_path.read_bytes())
            except Exception:
                pass

    (out_dir / "README.md").write_text(BUNDLE_README, encoding="utf-8")

    print(f"  Wrote bundle to: {out_dir}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="Output folder for the light bundle")
    ap.add_argument(
        "--dark-out",
        default=None,
        help="Output folder for the dark bundle (default: <out>-dark)",
    )
    ap.add_argument(
        "--no-dark",
        action="store_true",
        help="Skip generating the dark bundle",
    )
    args = ap.parse_args()

    # ── Light bundle ──
    out_dir = Path(args.out)

    print("Light bundle:")
    _write_bundle(out_dir, DEFAULT_THEME)

    # ── Dark bundle ──
    if not args.no_dark:
        dark_out = Path(args.dark_out) if args.dark_out else Path(str(args.out) + "-dark")

        print("Dark bundle:")
        _write_bundle(dark_out, DARK_THEME, dark=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
